version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: database
    volumes:
      - ./data:/var/lib/postgresql/data
  app:
    image: openjdk:17
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "./gradlew build && java -jar build/libs/myapp.jar"
    ports:
      - 8080:8080
    depends_on:
      - db